### ISSUE TITLE
FloodScan - Don't need `_AREA` in band name

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/ds-raster-pipelines#43]
I don't see why we need `_AREA` in band name? Could just be `SFED` or `MFED`... it's not really area exactly anyway more like %

**Comment by isatotun** [comment]
This seems to come from the historical .nc file. I will rename it to just SFED or MFED to match the new files as well.

**Comment by t-downing** [comment]
One argument for keeping `_AREA`- Floodscan calls their high-res product `SFED`, and their low-res aggregation (which is the product we get) `SFED_AREA`, because it's the fraction of the area that is "SFED". So if we ever use the high-res product, it might be confusing if we've re-named the low-res product to just `SFED`

**Comment by zackarno** [comment]
@t-downing  on the flip side: If they were both `SFED` then our scripts would be more compatible across products. I don't think we need to use the band name to track the version of product.

**Comment by t-downing** [comment]
Ah yeah fair, I guess it's just an aggregation of the same indicator, so would make sense to keep the name consistent across both.
